INPUT_CONFIG:
  x_min: 0
  x_max: 70
  x_grid_size: 0.2
  y_min: -40
  y_max: 40
  y_grid_size: 0.2
  z_min: -2.2
  z_max: 1
  z_grid_size: 0.2
  z_pillar_size: 4
  num_point_features: 3
  num_conseq_frames: 5
  num_reg_targets: 6
  num_classes: 1
  dim_gt_targets: 6
  max_targets_forever: 50
  anchors: [[3.4, 1.5], [3.9, 1.6], [4.4, 1.8]] #, [3.2, 6.4], [6.4, 3.2], [6.0, 2.0], [2.0, 6.0]]
  get_labels: 'all'
  z_center: -1
  z_height: 1.5
  dt: 0.1
  pp_max_points: 35
  pp_max_voxels: 20000
  pp_reverse_index: False
  pp_num_filters: [64]
  use_pp: True
  pp_use_norm: True
  pp_with_distance: False
  pp_verbose: False

MODEL_CONFIG:
  model: 'fafe'  # little_fafe or fafe

LOSS_CONFIG:
  confidence_threshold: 0.75
  lower_match_threshold: 0.4
  higher_match_threshold: 0.5
  lambda_time_decay: 0.97
  alpha_factor: 0.95
  gamma: 2
  regression_beta: 1
  regression_loss: 'SmoothL1'  # 'SmoothL1' or 'MSE'
  euler_beta: 1
  euler_loss: 'SmoothL1' # 'SmoothL1' or 'MSE'
  class_beta: 10

TRAIN_CONFIG:
  max_epochs: 20
  batch_size: 1
  num_workers: 0
  shuffle: True
  use_cuda: False
  cuda_device: 0
  verbose: True
  use_visdom: False
  visdom_port: 8098
  training_seqs: [0000, 0001, 0002]
  validation_seqs: [0002]
  learning_rate: 1e-4  #5e-3, # 1e-3
  weight_decay: 1e-4
  save_weights_modulus: 5
  plot_grad_flow: True

EVAL_CONFIG:
  batch_size: 1
  num_workers: 1
  use_cuda: False
  verbose: False
  use_visdom: False
  confidence_threshold: 0.5
  save_figs: False
  show_confidence: True
  infer_color: [1, 1, 1]
  gt_color: [0.8, 0.4, 0.9]
  validation_seqs: [0]
  anchors: [[3.4, 1.5], [3.9, 1.6], [4.4, 1.8]] #, [3.2, 6.4], [6.4, 3.2], [6.0, 2.0], [2.0, 6.0]]
  off_screen_rendering: False
  save_detections_as_measurements: True
  distance_threshold: 1
  save_raw: True

POST_CONFIG:
  iou_threshold: 0.5
  reason_distance_threshold: 1
  det2pred_distance_threshold: 1.2
  over_time_distance_threshold: 1
  confidence_threshold: 0.7
  verbose: False
  coordinate_transform: True